version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/CML-Backend-main
hooks:
  ApplicationStart:
    - location: scripts/after_install.sh
    - location: scripts/application_start.sh
