version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/CML-Backend-main/
permissions:
  - object: /home/ec2-user/CML-Backend-main/
    pattern: "**"
    owner: ec2-user
    group: ec2-user
    mode: 0755
hooks:
  BeforeInstall:
    - location: scripts/install_dependencies.sh
      timeout: 300
      runas: ec2-user
  AfterInstall:
    - location: scripts/start_application.sh
      timeout: 300
      runas: ec2-user
