version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/CML-Backend-main
hooks:
  BeforeInstall:
    - location: scripts/before_install.sh
      runas: ec2-user
  AfterInstall:
    - location: scripts/after_install.sh
      runas: ec2-user
  ApplicationStart:
    - location: scripts/application_start.sh
      runas: ec2-user
  ApplicationStop:
    - location: scripts/application_stop.sh
      runas: ec2-user
